### ISSUE TITLE
New SCSS Files Aren't Being Captured on Local Build

### ISSUE THREAD

**Issue by tpage99** [sgfdevs/sgf-dev-scratch-ui#10]
I'm thinking this is something I'm just doing wrong - I haven't messed with SCSS in some time - but I'm having trouble with local builds not recognizing new SCSS files. 

Use case: working on the about page and needed to add additional classes. Based on the current convention, created new file for classes and CSS is just not getting picked up at all from what I can see in dev tools. However, if I modify an existing file I pulled down from repo it works just fine (so adding my classes to the about_banner.scss file for instance works but a new about_landing.scss file isn't recognized).  

Tried the `npm run css` and stopping and restarting local build but no dice. I spent about 30 minutes on it trying to figure out what I'm screwing up, but I am at a bit of a loss. I'm used to Gatsby just running a `gatsby clean` and it clears the cache and all that mess - so not sure if there's a C# equivalent? I have tried deleting `package-lock.json` and `node modules` and running `npm install` again without success. Would appreciate any direction or debugging methodology pointers here. 

Link to repo for this branch: https://github.com/tpage99/sgf-dev-scratch-ui/tree/about-page

**Comment by tpage99** [comment]
@mykebates I don't know if it's more preferable for these to go in issues or if it's better to ping you in slack. For the sake of other potential newbies getting involved here I figured it was best served to drop comments here in issues but just hit me up if you want to run this another way.

**Comment by mykebates** [comment]
Ideally we'd have some documentation worth a dang! So GH issues is totally fine and even appreciated :)

I suspect the missing link in this equation is adding the "import" statement to the relevant folder's _index.scss file.

Each parent directory under assets/sass contains a _index.scss file that is responsible for importing each scss file in the given directory. BTW, this is not some sort of SASS/SCSS specific thing, just a personal pattern.

So if you look at assets/sass/modules/_index.scss you will see a list of @import "file_name"; (without the .scss extension). So for each new file you add you must also import that file.

In this case, in the assets/sass/modules/_index.scss file simply append
`@import "about_banner"`;

As long as the styling in the file is scoped to self: IE: everything nested inside of the class name "about_landing" - then it should not much matter where that @import statement is located at in the _index.scss file. Sass will render it top->down, but again, as long as it is not colliding with anything in the cascade, it will be fine at the bottom of that _index.scss file.

Please report back if this is the solution to the situation.

**Comment by tpage99** [comment]
Man, yeah that was it. Sorry I was looking for a lot more complicated solution and I should have just traced back to how styles were getting onto the page. 

Worked like a dream. 

I'll have to read up on this scoping. Seems like it would be a helpful method for specificity - I've just never used it to that extent but can definitely get on board with the mindset. Is this called anything in particular or is there documentation for this kind of pattern that I could read up on best practices? I've only solo dev'd so this is great practice for me to learn about other patterns people use.

**Comment by mykebates** [comment]
All good! Glad it was simple fix and not something more hairy.

On the "scoping" bit... that sounded a lot more deep than it needed to. The gist of the scoping asepct is actually the "C" in CSS - how styles "cascade". 

The approach I personally take is talked about a little bit in the walkthrough video around the [26 min mark](https://youtu.be/_1LPDkkAvW4?t=1556).  Although there is not necessarily a specific term to refer to this "style"... it can kind of be thought of as a "component" design approach or even a lite version [Atomic Design](https://atomicdesign.bradfrost.com/chapter-2/) (specifically similar to Atoms and Molecules in that analogy).

We'll chat further on this on Slack and such :)
