### ISSUE TITLE
New to .NET Core - Errors on setup

### ISSUE THREAD

**Issue by tpage99** [sgfdevs/sgf-dev-scratch-ui#3]
Couldn't get zsh to pick up dotnet command but managed to resolve that updating `~/.zshrc` file. 

Tried deleting `package-lock.json` and `yarn.lock` and re-doing `npm install` and then `dotnet run` but still getting loads of errors. 

Getting a handful of errors related to the SGFDevsUI.csproj file and noted that `TargetFramework` was pointed at 2.1 still. Updated to 3.1 per https://docs.microsoft.com/en-us/dotnet/standard/frameworks and got a fresh new set of errors. Gonna call it a night tonight at least, but since I'm primarily a React.js guy, if y'all have any tips or docs you can point me to so I can work my way through errors like this I'd appreciate it. 

`/usr/local/share/dotnet/sdk/3.1.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets(151,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [/Users/taylorpage/sgfdevs/sgf-dev-scratch-ui/SGFDevsUI.csproj]`

`/usr/local/share/dotnet/sdk/3.1.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.DefaultItems.targets(151,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [/Users/taylorpage/sgfdevs/sgf-dev-scratch-ui/SGFDevsUI.csproj]`

`Startup.cs(7,28): error CS0234: The type or namespace name 'SpaServices' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?) [/Users/taylorpage/sgfdevs/sgf-dev-scratch-ui/SGFDevsUI.csproj]`

`Pages/Build.cshtml.cs(14,17): warning CS0618: 'IHostingEnvironment' is obsolete: 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.' [/Users/taylorpage/sgfdevs/sgf-dev-scratch-ui/SGFDevsUI.csproj]`

`Startup.cs(29,56): warning CS0618: 'IHostingEnvironment' is obsolete: 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.' [/Users/taylorpage/sgfdevs/sgf-dev-scratch-ui/SGFDevsUI.csproj]`

`Pages/Build.cshtml.cs(29,22): warning CS0618: 'IHostingEnvironment' is obsolete: 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.' [/Users/taylorpage/sgfdevs/sgf-dev-scratch-ui/SGFDevsUI.csproj]`

`The build failed. Fix the build errors and run again.`

**Comment by tpage99** [comment]
Alright - got it working locally using info from docs to migrate to 3.0: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#in-process-hosting-model 

Handful of changes, and obviously considering I'm new to this mess, I'm not sure if that's something you want to do or would rather stick with previous version. 

I'll throw up in a PR so you can take a look at it. Obviously feel free to ignore otherwise.

**Comment by mykebates** [comment]
Some further issues came of updating to 3.0 that prevented the Razor pages from recompiling on page reload. This should all be pretty buttoned up now. However there are still some warnings that will show on initial dotnet run in relation to IHostingEnvironment.. some of these features utilized in this older setup will killed off in the next major .NET release but this will not be an issue for us because we will have moved on from this environment well before that release.
